[package]
name = "kyber_rust"
version = "0.1.0"
edition = "2021"
authors = ["supinie <joshua@supinie.com>"]

description = "A rust implementation of the IND-CCA2-secure PQC KEM Kyber (https://pq-crystals.org/kyber/)"
readme = "README.md"

repository = "https://github.com/supinie/kyber_rust"

license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.12", features = ["cargo"] }
